name: APISIX Docker Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - alpine
          - centos
          - alpine-local
    env:
      APISIX_DOCKER_TAG: 2.3-${{ matrix.platform }}

    runs-on: ubuntu-latest
    env:
      APISIX_PATH: "./apisix-local"
    steps:
      - uses: actions/checkout@v2

      - name: Clone apisix for local test
        if: ${{ matrix.platform == 'alpine-local' }}
        run: |
          git clone http://github.com/apache/apisix apisix-local

      - name: Build and run
        run: |
          make build-on-${{ matrix.platform }}
          docker-compose -f ./compose/docker-compose.yaml up -d
          sleep 30
          docker logs compose_apisix_1

      - name: Test
        run: |
          curl http://127.0.0.1:9080/apisix/admin/routes/1 \
          -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
            {
            "uri": "/get",
            "upstream": {
                "type": "roundrobin",
                "nodes": {
                    "httpbin.org:80": 1
                }
            }
          }'

          result_code=`curl -I -m 10 -o /dev/null -s -w %{http_code} http://127.0.0.1:9080/get`
          if [[ $result_code -ne 200 ]];then
                  printf "result_code: %s\n" "$result_code"
                  exit 125
          fi
