name: Push apisix to Docker image
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - alpine
          - centos

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push apisix image to Docker Hub
        run:
          make push-multiarch-on-${{ matrix.platform }}
